# Constants

# Constants used by the 'security_type' field on the Secuity model.
SECURITY_TYPE_COMMON = 11
SECURITY_TYPE_PREFERRED = 12
SECURITY_TYPE_CONVERTIBLE = 23
SECURITY_TYPE_OPTION = 35
SECURITY_TYPE_WARRANT = 36

TRIGGER_NONE = 0
TRIGGER_SINGLE = 1
TRIGGER_DOUBLE = 2

STATUS_OUTSTANDING = 1
STATUS_CANCELLED = 2
STATUS_TRANSFERRED = 3
STATUS_EXERCISED = 4
STATUS_CONVERTED = 6
